In [29]:
import numpy as np
import pandas as pd


In [3]:
pd.Series([23,3,4,5])

0    23
1     3
2     4
3     5
dtype: int64

In [4]:
ser=pd.Series([23,3,4,5])
ser

0    23
1     3
2     4
3     5
dtype: int64

In [5]:
Etiketten = ['a', 'b', 'c']
meine_Liste = [10, 20, 30]  # Liste
arr = np.array([10, 20, 30])  # Array
d = {'a': 10, 'b': 20, 'c': 30}  # dict

In [6]:
pd.Series(Etiketten)

0    a
1    b
2    c
dtype: object

In [7]:
pd.Series(meine_Liste)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [10]:
arr,Etiketten

(array([10, 20, 30]), ['a', 'b', 'c'])

In [11]:
pd.Series(data=arr,index=Etiketten)

a    10
b    20
c    30
dtype: int32

In [12]:
d


{'a': 10, 'b': 20, 'c': 30}

In [13]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [14]:
i = ['q', 'a', 'b', 'c', 'c','y', 'a', 'a']
pd.Series(data = d, index= i)

q     NaN
a    10.0
b    20.0
c    30.0
c    30.0
y     NaN
a    10.0
a    10.0
dtype: float64

In [15]:
pd.Series(data='Steve')

0    Steve
dtype: object

In [16]:
pd.Series(data='S t e v e'.split())

0    S
1    t
2    e
3    v
4    e
dtype: object

In [17]:
pd.Series(data=10, index=['a', 'b', 'c'])

a    10
b    10
c    10
dtype: int64

In [18]:
pd.Series(data=range(3),index=range(3))

0    0
1    1
2    2
dtype: int64

In [19]:
meine_Liste.extend([30, 30, 30, 30])
meine_Tupel = tuple(meine_Liste)
meine_Liste, meine_Tupel

([10, 20, 30, 30, 30, 30, 30], (10, 20, 30, 30, 30, 30, 30))

In [21]:
ser = pd.Series([sum,print,len,set,type,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
3                <class 'set'>
4               <class 'type'>
5      <built-in function len>
dtype: object

In [26]:
pd.Series([sum,print,len,set,type,len])[0](meine_Liste)

180

In [34]:
ser

0    23
1     3
2     4
3     5
dtype: int64

In [36]:
mix_data=['Hallo',2,True]
mix_data

['Hallo', 2, True]

In [37]:
pd.Series(mix_data)[0], type(pd.Series(mix_data)[0])


('Hallo', str)

In [38]:
pd.Series(mix_data)[0],(mix_data)[0]

('Hallo', 'Hallo')

In [40]:
pd.Series(mix_data)[0], pd.Series(mix_data)[1]

('Hallo', 2)

In [41]:
pd.Series(mix_data)[0], type(pd.Series(mix_data)[1])

('Hallo', int)

In [42]:
type(ser)

pandas.core.series.Series

In [43]:
ser

0    23
1     3
2     4
3     5
dtype: int64

In [44]:
ser=pd.Series([2,3,6,5])
ser

0    2
1    3
2    6
3    5
dtype: int64

In [45]:
ser.dtype

dtype('int64')

In [47]:
*ser,ser.shape,ser.size,len(ser),ser.ndim

(2, 3, 6, 5, (4,), 4, 4, 1)

In [48]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [53]:
ser.keys()

RangeIndex(start=0, stop=4, step=1)

In [54]:
ser.values

array([2, 3, 6, 5], dtype=int64)

In [55]:
[i for i in ser]

[2, 3, 6, 5]

In [56]:
[i for i in ser.values]

[2, 3, 6, 5]

In [57]:
for i in ser:
    print(i)

2
3
6
5


In [58]:
ser.items

<bound method Series.items of 0    2
1    3
2    6
3    5
dtype: int64>

In [59]:
list(ser.items())

[(0, 2), (1, 3), (2, 6), (3, 5)]

In [63]:
for index, value in ser.items():
    print(f"Index : {index}, Value : {value}")

Index : 0, Value : 2
Index : 1, Value : 3
Index : 2, Value : 6
Index : 3, Value : 5


In [64]:
dict(ser.items())

{0: 2, 1: 3, 2: 6, 3: 5}

In [67]:
ser = pd.Series(data= np.random.randint(0,25,10), index=[i for i in "cbaefdgihj" ])
ser

c     2
b     9
a    14
e    13
f    12
d    10
g     5
i     2
h     3
j    16
dtype: int32

In [68]:
ser.sort_index(ascending=True)

a    14
b     9
c     2
d    10
e    13
f    12
g     5
h     3
i     2
j    16
dtype: int32

In [70]:
ser,ser.isin([5,9])

(c     2
 b     9
 a    14
 e    13
 f    12
 d    10
 g     5
 i     2
 h     3
 j    16
 dtype: int32,
 c    False
 b     True
 a    False
 e    False
 f    False
 d    False
 g     True
 i    False
 h    False
 j    False
 dtype: bool)

In [71]:
pd.Series([i for i in 'clarusway'])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [77]:
ser1 = pd.Series([1,2,3,4], index = ['USA', 'Germany', 'Russland', 'Japan'])
ser1

USA         1
Germany     2
Russland    3
Japan       4
dtype: int64

In [79]:
ser2 = pd.Series([1,2,3,4], index = ['USA', 'Germany', 'Italy', 'Japan'])
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [80]:
ser1.sort_index()

Germany     2
Japan       4
Russland    3
USA         1
dtype: int64

In [82]:
ser2.sort_values()

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [83]:
ser1['Germany']

2

In [84]:
ser1['Japan']

4

In [86]:
ser1

USA         1
Germany     2
Russland    3
Japan       4
dtype: int64

In [87]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [85]:
ser1+ser2

Germany     4.0
Italy       NaN
Japan       8.0
Russland    NaN
USA         2.0
dtype: float64

In [89]:
ser3 = pd.Series(data=['a','b','c','d'])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [91]:
ser3[0]

'a'

In [92]:
ser3[2:]

2    c
3    d
dtype: object

In [93]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

In [129]:
pan_ser = pd.Series(data=[121, 200, 150, 99], index=["terry", "steve", "matt", "johnson"])
pan_ser

terry      121
steve      200
matt       150
johnson     99
dtype: int64

In [95]:
pan_ser['terry']

121

In [96]:
pan_ser[0]

121

In [99]:
pan_ser

terry      121
steve      200
matt       150
johnson     99
dtype: int64

In [97]:
index_ = [0, 1, 2]

In [98]:
pan_ser[index_]

terry    121
steve    200
matt     150
dtype: int64

In [101]:
pan_ser[[0,1,2]]

terry    121
steve    200
matt     150
dtype: int64

In [103]:
pan_ser['terry':'matt']

terry    121
steve    200
matt     150
dtype: int64

In [104]:
pan_ser[0:3]

terry    121
steve    200
matt     150
dtype: int64

In [105]:
pan_ser.keys()

Index(['terry', 'steve', 'matt', 'johnson'], dtype='object')

In [108]:
pan_ser.keys()[0]

'terry'

In [109]:
pan_ser.index

Index(['terry', 'steve', 'matt', 'johnson'], dtype='object')

In [110]:
pan_ser.values

array([121, 200, 150,  99], dtype=int64)

In [115]:
pan_ser.items()

In [116]:
dict(pan_ser.items())

{'terry': 121, 'steve': 200, 'matt': 150, 'johnson': 99}

In [117]:
for index, value in pan_ser.items():
    print(index, value)

terry 121
steve 200
matt 150
johnson 99


In [119]:
'terry' in pan_ser

True

In [120]:
'bob' in pan_ser

False

In [121]:
pan_ser.isin([200, 150])

terry      False
steve       True
matt        True
johnson    False
dtype: bool

In [123]:
pan_ser[pan_ser.isin([200, 150])]

steve    200
matt     150
dtype: int64

In [124]:
pan_ser['terry'] = 90

In [125]:
pan_ser

terry       90
steve      200
matt       150
johnson     99
dtype: int64

In [126]:
pan_ser[1:2] = 90
pan_ser

terry       90
steve       90
matt       150
johnson     99
dtype: int64

In [133]:
pan_ser[pan_ser < 100] = 100
pan_ser

terry      121
steve      200
matt       150
johnson    100
dtype: int64

In [136]:
pan_ser[pan_ser > 155]


steve    200
dtype: int64

In [137]:
data = [1, 2, 39, 67, 90]
data

[1, 2, 39, 67, 90]

In [139]:
pd.DataFrame(data, columns=['column'])

column
0       1
1       2
2      39
3      67
4      90

In [141]:
data_= np.arange(1,10).reshape(3,3)
data_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
pd.DataFrame(data_ , columns=['var1','var2','var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [145]:
data__=np.arange(1,101).reshape(25,4)
df = pd.DataFrame(data__, columns=['var1','var2','var3','var4'])

In [146]:
df.head()

var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16
4    17    18    19    20

In [148]:
df.tail()

var1  var2  var3  var4
20    81    82    83    84
21    85    86    87    88
22    89    90    91    92
23    93    94    95    96
24    97    98    99   100

In [150]:
df.sample(3)

var1  var2  var3  var4
18    73    74    75    76
17    69    70    71    72
16    65    66    67    68

In [151]:
df.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [152]:
for i in df.columns:
    print(i)

var1
var2
var3
var4


In [153]:
df.columns = ['new1', 'new2','new3', 'new4']

In [154]:
df.columns

Index(['new1', 'new2', 'new3', 'new4'], dtype='object')

In [155]:
df.head(3)

new1  new2  new3  new4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12

In [156]:
type(df)

pandas.core.frame.DataFrame

In [157]:
df.shape

(25, 4)

In [158]:
df.ndim

2

In [159]:
df.size

100

In [160]:
len(df)

25