In [1]:
import pandas as pd
import numpy as np


In [2]:
daten_set = [1, 3, 5, 7, 9, 18]
columns = ['alter']
daten_set, columns

([1, 3, 5, 7, 9, 18], ['alter'])

In [4]:
pd.DataFrame(daten_set, columns = columns )

alter
0      1
1      3
2      5
3      7
4      9
5     18

In [5]:
daten_set = np.arange(1, 24, 2).reshape(3, 4)
daten_set

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [6]:
pd.DataFrame(daten_set, columns=['var1','var2','var3','var4'])

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [7]:
df = pd.DataFrame(data=daten_set, columns=['var1','var2','var3','var4'])
df

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [8]:
df.head(2)

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15

In [9]:
df.tail(2)

var1  var2  var3  var4
1     9    11    13    15
2    17    19    21    23

In [10]:
df.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [14]:
print("Zeil-Spalte:", df.shape, "Spalte:", df.shape[1],\
      "Dimention:",  df.ndim, "Größe:", df.size, "len:", len(df))

Zeil-Spalte: (3, 4) Spalte: 4 Dimention: 2 Größe: 12 len: 3


In [15]:
df

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [16]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [20]:
df.index.values

array([0, 1, 2], dtype=int64)

In [21]:
print("Index:", df.index.values, "Index[1]:", df.index[1])

Index: [0 1 2] Index[1]: 1


In [22]:
s1 = np.random.randint(2, 10, size = 4)
s2 = np.random.randint(3, 10, size = 4)
s3 = np.random.randint(4, 15, size = 4)

In [23]:
s1,s2,s3

(array([6, 8, 5, 7]), array([7, 7, 3, 9]), array([ 4,  9,  5, 11]))

In [24]:
dict_= {'var1':s1,'var2':s2,'var3':s3}

In [25]:
dict_

{'var1': array([6, 8, 5, 7]),
 'var2': array([7, 7, 3, 9]),
 'var3': array([ 4,  9,  5, 11])}

In [29]:
df_= pd.DataFrame(dict_)
df_

var1  var2  var3
0     6     7     4
1     8     7     9
2     5     3     5
3     7     9    11

In [28]:
df_.index

RangeIndex(start=0, stop=4, step=1)

In [30]:
df_.index = ["a", "b", "c", "d"]

In [31]:
df_

var1  var2  var3
a     6     7     4
b     8     7     9
c     5     3     5
d     7     9    11

In [32]:
'var2' in df_

True

In [33]:
5 in df_

False

In [41]:
a in df_.index.values

NameError: name 'a' is not defined

In [40]:
df_.index.values

array(['a', 'b', 'c', 'd'], dtype=object)

In [66]:
from numpy.random import randn
np.random.seed(101)

In [65]:
df = pd.DataFrame(data= np.random.randn(5,4), 
                  index = 'A B C D E'.split(), 
                  columns='X Y W Z'.split())
df

X         Y         W         Z
A  0.327845  0.674485 -0.174057  0.780140
B -0.383258 -0.409318  0.343539  0.196275
C -0.982776  2.231555 -0.971393 -1.522333
D  1.133703  0.528187  0.393461 -0.630507
E -1.398290 -0.219311 -0.045676  0.012421

In [67]:
pd.DataFrame(randn(5, 4), 'a b c d e'.split(), 'w x y z'.split())

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [70]:
pd.DataFrame(randn(5, 4), columns='w x y z'.split(), index='a b c d e'.split())

w         x         y         z
a -0.993263  0.196800 -1.136645  0.000366
b  1.025984 -0.156598 -0.031579  0.649826
c  2.154846 -0.610259 -0.755325 -0.346419
d  0.147027 -0.479448  0.558769  1.024810
e -0.925874  1.862864 -1.133817  0.610478

In [72]:
df = pd.DataFrame(data= np.random.randn(5,4), 
                  index = 'A B C D E'.split(), 
                  columns='X Y W Z'.split())
df

X         Y         W         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [73]:
df['Y']

A    2.084019
B    1.035125
C   -0.741790
D    1.482495
E    1.192241
Name: Y, dtype: float64

In [74]:
df.Y

A    2.084019
B    1.035125
C   -0.741790
D    1.482495
E    1.192241
Name: Y, dtype: float64

In [75]:
df['Y']

(A    2.084019
 B    1.035125
 C   -0.741790
 D    1.482495
 E    1.192241
 Name: Y, dtype: float64,
 pandas.core.frame.DataFrame)

In [79]:
type(df)

pandas.core.frame.DataFrame

In [80]:
type(df['Y'])

pandas.core.series.Series

In [81]:
df['Y']

A    2.084019
B    1.035125
C   -0.741790
D    1.482495
E    1.192241
Name: Y, dtype: float64

In [82]:
df[['Y']]

Y
A  2.084019
B  1.035125
C -0.741790
D  1.482495
E  1.192241

In [83]:
type(df['Y'])

pandas.core.series.Series

In [86]:
type(df[['Y']])

pandas.core.frame.DataFrame

In [87]:
df[['Z','X']]

Z         X
A  0.230336  0.386030
B  1.939932  0.681209
C -0.732845 -1.005187
D -2.141212 -1.382920
E  1.292765  0.992573

In [89]:
df['Z']

A    0.230336
B    1.939932
C   -0.732845
D   -2.141212
E    1.292765
Name: Z, dtype: float64

In [90]:
df['X':'Z']

Empty DataFrame
Columns: [X, Y, W, Z]
Index: []

In [91]:
df['B':'C']

X         Y         W         Z
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845

In [92]:
df

X         Y         W         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [93]:
df["B":"C"][["Y", "Z"]]

Y         Z
B  1.035125  1.939932
C -0.741790 -0.732845

In [94]:
df

X         Y         W         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [97]:
df['X*Y'] = df['X'] * df['Y']

In [98]:
df

X         Y         W         Z       x*y       X*Y
A  0.386030  2.084019 -0.376519  0.230336  0.804494  0.804494
B  0.681209  1.035125 -0.031160  1.939932  0.705137  0.705137
C -1.005187 -0.741790  0.187125 -0.732845  0.745637  0.745637
D -1.382920  1.482495  0.961458 -2.141212 -2.050173 -2.050173
E  0.992573  1.192241 -1.046780  1.292765  1.183386  1.183386

In [102]:
df.drop(labels= 'x*y',axis=1, inplace=True)

In [103]:
df

X         Y         W         Z       X*Y
A  0.386030  2.084019 -0.376519  0.230336  0.804494
B  0.681209  1.035125 -0.031160  1.939932  0.705137
C -1.005187 -0.741790  0.187125 -0.732845  0.745637
D -1.382920  1.482495  0.961458 -2.141212 -2.050173
E  0.992573  1.192241 -1.046780  1.292765  1.183386

In [104]:
df.drop(labels= 'X*Y',axis=1, inplace=True)

In [105]:
df

X         Y         W         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [106]:
df.drop('C', axis=0)

X         Y         W         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
D -1.382920  1.482495  0.961458 -2.141212
E  0.992573  1.192241 -1.046780  1.292765

In [107]:
df.drop(['E','D'], axis=0)

X         Y         W         Z
A  0.386030  2.084019 -0.376519  0.230336
B  0.681209  1.035125 -0.031160  1.939932
C -1.005187 -0.741790  0.187125 -0.732845

In [108]:
daten_set = np.random.randint(1, 40, size=(8, 4))
df = pd.DataFrame(daten_set, columns = ["var1","var2","var3",'var4'])
df

var1  var2  var3  var4
0    12    28    34    25
1    37    39    10     4
2     2    16     5     5
3    37    19    15    29
4    18    24    17     7
5     8    21    11    33
6    24    23    22    27
7    13     3    18     2

In [109]:
df.loc[4]

var1    18
var2    24
var3    17
var4     7
Name: 4, dtype: int32

In [111]:
df.loc[[4]]

var1  var2  var3  var4
4    18    24    17     7

In [112]:
df.loc[4]

var1    18
var2    24
var3    17
var4     7
Name: 4, dtype: int32

In [113]:
df

var1  var2  var3  var4
0    12    28    34    25
1    37    39    10     4
2     2    16     5     5
3    37    19    15    29
4    18    24    17     7
5     8    21    11    33
6    24    23    22    27
7    13     3    18     2

In [114]:
df.loc[2:5]

var1  var2  var3  var4
2     2    16     5     5
3    37    19    15    29
4    18    24    17     7
5     8    21    11    33

In [115]:
df.iloc[2:5]

var1  var2  var3  var4
2     2    16     5     5
3    37    19    15    29
4    18    24    17     7

In [116]:
df.index='a b c d e f g h'.split()
df

var1  var2  var3  var4
a    12    28    34    25
b    37    39    10     4
c     2    16     5     5
d    37    19    15    29
e    18    24    17     7
f     8    21    11    33
g    24    23    22    27
h    13     3    18     2

In [117]:
df.iloc[1:4]

var1  var2  var3  var4
b    37    39    10     4
c     2    16     5     5
d    37    19    15    29

In [118]:
df

var1  var2  var3  var4
a    12    28    34    25
b    37    39    10     4
c     2    16     5     5
d    37    19    15    29
e    18    24    17     7
f     8    21    11    33
g    24    23    22    27
h    13     3    18     2

In [119]:
df.loc['c':'g']

var1  var2  var3  var4
c     2    16     5     5
d    37    19    15    29
e    18    24    17     7
f     8    21    11    33
g    24    23    22    27

In [120]:
df.iloc[4, 1]

24

In [121]:
df.iloc[:, 1]

a    28
b    39
c    16
d    19
e    24
f    21
g    23
h     3
Name: var2, dtype: int32

In [122]:
df.loc['d':'g', 'var3']

d    15
e    17
f    11
g    22
Name: var3, dtype: int32

In [123]:
df.loc[:, 'var3']


a    34
b    10
c     5
d    15
e    17
f    11
g    22
h    18
Name: var3, dtype: int32

In [124]:
df.loc['d':'g'][['var3']]

var3
d    15
e    17
f    11
g    22

In [126]:
df.loc['d':'g']['var3']

d    15
e    17
f    11
g    22
Name: var3, dtype: int32

In [127]:
df.loc['d':'g', ["var3"]]

var3
d    15
e    17
f    11
g    22

In [128]:
df.loc['d':'g', "var3"]

d    15
e    17
f    11
g    22
Name: var3, dtype: int32

In [129]:
df

var1  var2  var3  var4
a    12    28    34    25
b    37    39    10     4
c     2    16     5     5
d    37    19    15    29
e    18    24    17     7
f     8    21    11    33
g    24    23    22    27
h    13     3    18     2

In [130]:
df.iloc[2:5, 2]

c     5
d    15
e    17
Name: var3, dtype: int32

In [131]:
df.iloc[2:5][['var2']]

var2
c    16
d    19
e    24

In [132]:
df = pd.DataFrame(randn(5, 4),
                    index='A B C D E'.split(),
                    columns='W X Y Z'.split())
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [133]:
df.loc['C']

W   -0.605139
X   -1.086494
Y    1.106352
Z    0.268191
Name: C, dtype: float64

In [134]:
df.loc[['C']]

W         X         Y         Z
C -0.605139 -1.086494  1.106352  0.268191

In [135]:
df.iloc[2]

W   -0.605139
X   -1.086494
Y    1.106352
Z    0.268191
Name: C, dtype: float64

In [136]:
type(df.iloc[2])

pandas.core.series.Series

In [137]:
df.iloc[2].values

array([-0.6051392 , -1.08649425,  1.10635226,  0.26819141])

In [138]:
df.iloc[[2]]

W         X         Y         Z
C -0.605139 -1.086494  1.106352  0.268191

In [139]:
type(df.iloc[[2]])

pandas.core.frame.DataFrame

In [140]:
df.iloc[[2]].values

array([[-0.6051392 , -1.08649425,  1.10635226,  0.26819141]])

In [141]:
df.loc[['C']]

W         X         Y         Z
C -0.605139 -1.086494  1.106352  0.268191

In [142]:
df.iloc[[2]]

W         X         Y         Z
C -0.605139 -1.086494  1.106352  0.268191

In [143]:
df.iloc[:, 2]

A   -1.462832
B   -0.732374
C    1.106352
D    0.967432
E   -0.455352
Name: Y, dtype: float64

In [144]:
df.iloc[:,[2]]

Y
A -1.462832
B -0.732374
C  1.106352
D  0.967432
E -0.455352

In [145]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [146]:
df[['Y','X']]

Y         X
A -1.462832 -0.198045
B -0.732374 -0.588251
C  1.106352 -1.086494
D  0.967432  0.944667
E -0.455352  0.924213

In [148]:
df['Y','X'] # tek parantez seri oluyor

KeyError: ('Y', 'X')

In [149]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [150]:
df.loc['C','Z']

0.26819141112095735

In [151]:
df.loc[['C'],['Z']]

Z
C  0.268191

In [152]:
df.loc[['A','C'],['W','Z']]

W         Z
A -1.299735  1.148300
C -0.605139  0.268191

In [154]:
df.loc[['A','C']][['W','Z']]

W         Z
A -1.299735  1.148300
C -0.605139  0.268191

In [155]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [156]:
df.iloc[[0,  2], [0, 3]]

W         Z
A -1.299735  1.148300
C -0.605139  0.268191

In [157]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [158]:
df > 0.5

W      X      Y      Z
A  False  False  False   True
B  False  False  False  False
C  False  False   True  False
D  False   True   True  False
E   True   True  False   True

In [159]:
df[df > 0.5]

W         X         Y         Z
A       NaN       NaN       NaN  1.148300
B       NaN       NaN       NaN       NaN
C       NaN       NaN  1.106352       NaN
D       NaN  0.944667  0.967432       NaN
E  0.715678  0.924213       NaN  0.508705

In [161]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [160]:
df[df['Z'] > 0.5]

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
E  0.715678  0.924213 -0.455352  0.508705

In [163]:
df[df['Z'] > 0.5][['Z']]

Z
A  1.148300
E  0.508705

In [164]:
df[['Z']]

Z
A  1.148300
B -0.644242
C  0.268191
D -0.641797
E  0.508705

In [165]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [166]:
df[df['X'] < 1][['W']]

W
A -1.299735
B -0.593557
C -0.605139
D  0.463486
E  0.715678

In [167]:
df[df['Y'] > 0][['Z', 'W', 'Y']]

Z         W         Y
C  0.268191 -0.605139  1.106352
D -0.641797  0.463486  0.967432

In [168]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [169]:
df[(df['W'] > 0) & (df['Y'] < 1)]

W         X         Y         Z
D  0.463486  0.944667  0.967432 -0.641797
E  0.715678  0.924213 -0.455352  0.508705

In [170]:
df[(df['W'] > 0) & (df['Y'] < 1)] = 0
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.000000  0.000000  0.000000  0.000000
E  0.000000  0.000000  0.000000  0.000000

In [174]:
df.loc[(df.X < 0), ['X','Z']]

X         Z
A -0.198045  1.148300
B -0.588251 -0.644242
C -1.086494  0.268191

In [173]:
df.loc[(df.X <= 0), ['X','Z']]

X         Z
A -0.198045  1.148300
B -0.588251 -0.644242
C -1.086494  0.268191
D  0.000000  0.000000
E  0.000000  0.000000

In [176]:
df.loc[(df.X < 0)][['X','Z']]

X         Z
A -0.198045  1.148300
B -0.588251 -0.644242
C -1.086494  0.268191

In [177]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.000000  0.000000  0.000000  0.000000
E  0.000000  0.000000  0.000000  0.000000

In [178]:
df.loc[((df.W > 1) | (df.Y < 1)), ['Y','Z']]

Y         Z
A -1.462832  1.148300
B -0.732374 -0.644242
D  0.000000  0.000000
E  0.000000  0.000000

In [179]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.000000  0.000000  0.000000  0.000000
E  0.000000  0.000000  0.000000  0.000000

In [182]:
df.reset_index()


index         W         X         Y         Z
0     A -1.299735 -0.198045 -1.462832  1.148300
1     B -0.593557 -0.588251 -0.732374 -0.644242
2     C -0.605139 -1.086494  1.106352  0.268191
3     D  0.000000  0.000000  0.000000  0.000000
4     E  0.000000  0.000000  0.000000  0.000000

In [183]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.000000  0.000000  0.000000  0.000000
E  0.000000  0.000000  0.000000  0.000000

In [184]:
df.reset_index(drop=True)

W         X         Y         Z
0 -1.299735 -0.198045 -1.462832  1.148300
1 -0.593557 -0.588251 -0.732374 -0.644242
2 -0.605139 -1.086494  1.106352  0.268191
3  0.000000  0.000000  0.000000  0.000000
4  0.000000  0.000000  0.000000  0.000000

In [185]:
df

W         X         Y         Z
A -1.299735 -0.198045 -1.462832  1.148300
B -0.593557 -0.588251 -0.732374 -0.644242
C -0.605139 -1.086494  1.106352  0.268191
D  0.000000  0.000000  0.000000  0.000000
E  0.000000  0.000000  0.000000  0.000000

In [186]:
neueindx = 'CA NY WY OR CO'.split()
neueindx

['CA', 'NY', 'WY', 'OR', 'CO']

In [187]:
df['neueidx'] = neueindx
df

W         X         Y         Z neueidx
A -1.299735 -0.198045 -1.462832  1.148300      CA
B -0.593557 -0.588251 -0.732374 -0.644242      NY
C -0.605139 -1.086494  1.106352  0.268191      WY
D  0.000000  0.000000  0.000000  0.000000      OR
E  0.000000  0.000000  0.000000  0.000000      CO

In [188]:
df.set_index('neueidx')

W         X         Y         Z
neueidx                                        
CA      -1.299735 -0.198045 -1.462832  1.148300
NY      -0.593557 -0.588251 -0.732374 -0.644242
WY      -0.605139 -1.086494  1.106352  0.268191
OR       0.000000  0.000000  0.000000  0.000000
CO       0.000000  0.000000  0.000000  0.000000

In [189]:
df

W         X         Y         Z neueidx
A -1.299735 -0.198045 -1.462832  1.148300      CA
B -0.593557 -0.588251 -0.732374 -0.644242      NY
C -0.605139 -1.086494  1.106352  0.268191      WY
D  0.000000  0.000000  0.000000  0.000000      OR
E  0.000000  0.000000  0.000000  0.000000      CO

In [190]:
# Indexstufen
stufe1 = [1, 2, 3, 1, 2, 3, 5, 6, 7]
stufe2 = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2','M3', 'M3', 'M3']
multi_index = list(zip(stufe2 , stufe1))
multi_index

[('M1', 1),
 ('M1', 2),
 ('M1', 3),
 ('M2', 1),
 ('M2', 2),
 ('M2', 3),
 ('M3', 5),
 ('M3', 6),
 ('M3', 7)]

In [191]:
index_ = pd.MultiIndex.from_tuples(multi_index)
index_

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3),
            ('M3', 5),
            ('M3', 6),
            ('M3', 7)],
           )

In [192]:
df = pd.DataFrame(np.random.randn(9, 4), 
                  index=index_, 
                  columns=['A','B','C','D'])
df

A         B         C         D
M1 1  1.686476  0.956232  0.148875 -2.028439
   2 -0.714869 -0.872331  1.836753  0.862782
   3  1.506899  0.049270  0.816299 -1.607242
M2 1 -0.807731 -1.096354 -0.789084  1.286486
   2  0.274132 -0.880482  1.066049 -1.394954
   3  0.304737 -0.595581  0.107576  0.453847
M3 5 -0.756019 -1.118859  1.828815 -0.720654
   6 -2.052395 -1.325425 -0.518817 -1.387928
   7 -0.466770 -1.174098 -0.077359  1.366345

In [193]:
np.random.randn(9, 4)

array([[ 1.24158911, -2.91988653,  0.54754718,  0.29450636],
       [-1.68170859, -0.64363783, -1.50478877, -0.01841154],
       [ 0.81892044,  0.92124261, -0.42095281, -1.4807182 ],
       [-0.73803932, -2.10153999,  0.093586  , -0.353061  ],
       [ 0.85000859, -1.05766654,  0.87786041, -0.36941163],
       [-0.65897426,  0.51766227,  0.55246743,  1.40673884],
       [-0.60529567,  0.32413097, -0.68569202,  0.2048492 ],
       [ 1.67789543, -0.87427404,  0.1114784 ,  1.54642261],
       [-0.1900138 , -0.9344658 , -1.25622596, -0.44793543]])

In [194]:
df

A         B         C         D
M1 1  1.686476  0.956232  0.148875 -2.028439
   2 -0.714869 -0.872331  1.836753  0.862782
   3  1.506899  0.049270  0.816299 -1.607242
M2 1 -0.807731 -1.096354 -0.789084  1.286486
   2  0.274132 -0.880482  1.066049 -1.394954
   3  0.304737 -0.595581  0.107576  0.453847
M3 5 -0.756019 -1.118859  1.828815 -0.720654
   6 -2.052395 -1.325425 -0.518817 -1.387928
   7 -0.466770 -1.174098 -0.077359  1.366345

In [195]:
df.loc['M1']

A         B         C         D
1  1.686476  0.956232  0.148875 -2.028439
2 -0.714869 -0.872331  1.836753  0.862782
3  1.506899  0.049270  0.816299 -1.607242

In [197]:
df.loc['M1'].loc[[2]]

A         B         C         D
2 -0.714869 -0.872331  1.836753  0.862782

In [198]:
df.index.names

FrozenList([None, None])

In [199]:
df.index.names = ['Group','Num']

In [200]:
df

A         B         C         D
Group Num                                        
M1    1    1.686476  0.956232  0.148875 -2.028439
      2   -0.714869 -0.872331  1.836753  0.862782
      3    1.506899  0.049270  0.816299 -1.607242
M2    1   -0.807731 -1.096354 -0.789084  1.286486
      2    0.274132 -0.880482  1.066049 -1.394954
      3    0.304737 -0.595581  0.107576  0.453847
M3    5   -0.756019 -1.118859  1.828815 -0.720654
      6   -2.052395 -1.325425 -0.518817 -1.387928
      7   -0.466770 -1.174098 -0.077359  1.366345

In [201]:
df.xs('M1')

A         B         C         D
Num                                        
1    1.686476  0.956232  0.148875 -2.028439
2   -0.714869 -0.872331  1.836753  0.862782
3    1.506899  0.049270  0.816299 -1.607242

In [203]:
df.loc['M1']

A         B         C         D
Num                                        
1    1.686476  0.956232  0.148875 -2.028439
2   -0.714869 -0.872331  1.836753  0.862782
3    1.506899  0.049270  0.816299 -1.607242

In [204]:
df

A         B         C         D
Group Num                                        
M1    1    1.686476  0.956232  0.148875 -2.028439
      2   -0.714869 -0.872331  1.836753  0.862782
      3    1.506899  0.049270  0.816299 -1.607242
M2    1   -0.807731 -1.096354 -0.789084  1.286486
      2    0.274132 -0.880482  1.066049 -1.394954
      3    0.304737 -0.595581  0.107576  0.453847
M3    5   -0.756019 -1.118859  1.828815 -0.720654
      6   -2.052395 -1.325425 -0.518817 -1.387928
      7   -0.466770 -1.174098 -0.077359  1.366345

In [205]:
df.xs(['M1',2])

C:\Users\bulen\AppData\Local\Temp/ipykernel_53016/1792420767.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['M1',2])


A   -0.714869
B   -0.872331
C    1.836753
D    0.862782
Name: (M1, 2), dtype: float64

In [207]:
from sklearn import datasets
import seaborn as sns

In [208]:
df = sns.load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [209]:
df.shape

(150, 5)

In [210]:
df.ndim

2

In [211]:
df.size

750

In [212]:
df.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [213]:
df.sample(2)

sepal_length  sepal_width  petal_length  petal_width species
32           5.2          4.1           1.5          0.1  setosa
47           4.6          3.2           1.4          0.2  setosa

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [218]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [219]:
df.species.value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [220]:
df.mean()

C:\Users\bulen\AppData\Local\Temp/ipykernel_53016/3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [222]:
df.loc[:,'sepal_length':'petal_width'].mean()

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [224]:
df.drop(['species'],axis=1).mean()

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

In [225]:
df.sum(axis=1)

C:\Users\bulen\AppData\Local\Temp/ipykernel_53016/1459321664.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.sum(axis=1)


0      10.2
1       9.5
2       9.4
3       9.4
4      10.2
       ... 
145    17.2
146    15.7
147    16.7
148    17.3
149    15.8
Length: 150, dtype: float64

In [226]:
df.drop(['species'],axis=1).sum(axis=1)

0      10.2
1       9.5
2       9.4
3       9.4
4      10.2
       ... 
145    17.2
146    15.7
147    16.7
148    17.3
149    15.8
Length: 150, dtype: float64

In [227]:
df.drop(['species'],axis=1).sum()

sepal_length    876.5
sepal_width     458.6
petal_length    563.7
petal_width     179.9
dtype: float64

In [229]:
df.sepal_length.sum()

876.5

In [230]:
df.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [231]:
df.iloc[0:6 ,0:]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa

In [232]:
df.loc[0:6, :]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa

In [234]:
df[(df.sepal_length > 5) & (df.sepal_width > 3)]

sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
5             5.4          3.9           1.7          0.4      setosa
10            5.4          3.7           1.5          0.2      setosa
14            5.8          4.0           1.2          0.2      setosa
15            5.7          4.4           1.5          0.4      setosa
16            5.4          3.9           1.3          0.4      setosa
17            5.1          3.5           1.4          0.3      setosa
18            5.7          3.8           1.7          0.3      setosa
19            5.1          3.8           1.5          0.3      setosa
20            5.4          3.4           1.7          0.2      setosa
21            5.1          3.7           1.5          0.4      setosa
23            5.1          3.3           1.7          0.5      setosa
27            5.2          3.5           1.5          0.2      setosa
28            5.2          3.4           1.4          0.2      setosa
31            5.4          3.4           1.5          0.4      setosa
32            5.2          4.1           1.5          0.1      setosa
33            5.5          4.2           1.4          0.2      setosa
36            5.5          3.5           1.3          0.2      setosa
39            5.1          3.4           1.5          0.2      setosa
44            5.1          3.8           1.9          0.4      setosa
46            5.1          3.8           1.6          0.2      setosa
48            5.3          3.7           1.5          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
56            6.3          3.3           4.7          1.6  versicolor
65            6.7          3.1           4.4          1.4  versicolor
70            5.9          3.2           4.8          1.8  versicolor
85            6.0          3.4           4.5          1.6  versicolor
86            6.7          3.1           4.7          1.5  versicolor
100           6.3          3.3           6.0          2.5   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
115           6.4          3.2           5.3          2.3   virginica
117           7.7          3.8           6.7          2.2   virginica
120           6.9          3.2           5.7          2.3   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
131           7.9          3.8           6.4          2.0   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
148           6.2          3.4           5.4          2.3   virginica

In [235]:
df[(df.sepal_length > 5) & (df.sepal_width > 3)].head()

sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa

In [237]:
df[(df.sepal_length > 5) & (df.sepal_width > 3)].count()

sepal_length    47
sepal_width     47
petal_length    47
petal_width     47
species         47
dtype: int64

In [238]:
df[(df.sepal_length > 5) & (df.sepal_width > 3)].sum()

sepal_length                                                284.5
sepal_width                                                 163.6
petal_length                                                167.6
petal_width                                                  56.2
species         setosasetosasetosasetosasetosasetosasetosaseto...
dtype: object

In [239]:
df.sort_values(by='species', ascending=True)

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
30            4.8          3.1           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]