___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 1</p><h1>

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1, 2, 3]
my_list

In [ ]:
type(my_list)

In [ ]:
my_array=np.array(my_list)
my_array


In [ ]:
type(my_array)

### Why NumPy?

In [ ]:
#liste 
a= [1,2,3,4]
b= [1,2,3,4]

In [ ]:
a*b

In [ ]:
a*3

In [ ]:
ab=[]
for i in range(len(a)):
    ab.append(a[i]*b[i])
print(ab)

In [ ]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [ ]:
a1*b1

In [ ]:
a1*3

In [ ]:
a1.ndim # boyutlari verir dimension

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
# ic ice liste

In [ ]:
type(my_matrix)

In [ ]:
new_matrix = np.array(my_matrix)
new_matrix

In [ ]:
type(new_matrix)

### Built-in Methods

There are lots of built-in ways to generate Arrays

### ``arange``

Return evenly spaced values within a given interval.

arange([start,] stop[, step,], dtype=None)

In [ ]:
np.arange(10)

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(0,11,2)

In [ ]:
np.arange(0,11,1.5)

In [ ]:
np.arange(0,31,3)

### ``linspace``
Return evenly spaced numbers over a specified interval.

np.linspace(start, stop, num=50)

In [ ]:
np.linspace(0,10) # hic yazmazsak number 50 dir 50 tane yazar

In [ ]:
np.linspace(0,10, num=9)

In [ ]:
np.linspace(0,10, num=20, dtype=int)

In [ ]:
set(np.linspace(0, 10, 51, dtype = "int"))
# np.linspace(0, 10, 50, dtype = "int")

### **``zeros``, ``ones`` and ``full``**

Generate arrays of zeros or ones

np.zeros(shape, dtype=float, order='C')

np.ones(shape, dtype=None, order='C')

np.full(shape, fill_value, dtype=None, order='C')

In [ ]:
np.zeros(3) # 0 elemanli float array üretir

In [ ]:
np.zeros(10, dtype=int)

In [ ]:
np.zeros((5,5))

In [ ]:
np.zeros((5,5),dtype=int)

In [ ]:
np.ones(3)

In [ ]:
np.ones(10, dtype=int)

In [ ]:
x=np.ones((4,4),dtype=str)
x

In [ ]:
type(x)

In [ ]:
np.ones((4,4),dtype=bool)

In [ ]:
np.zeros((4,4),dtype=bool)

In [ ]:
np.full((3, 5), "3", order = "C") 

# "C" C language "F" fortran language
# Whether to store multidimensional data in C- or Fortran-contiguous 
# (row- or column-wise) order in memory.

### ``eye``

Creates an [identity matrix](https://www.mathbootcamps.com/the-identity-matrix-and-its-properties/)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(4)

### Random 

Numpy also has lots of ways to create random number arrays:

### ``rand``
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

- ``(0, 5)`` = 1, 2, 3, 4
- ``(0, 5]`` = 1, 2, 3, 4, 5
- ``[0, 5)`` = 0, 1, 2, 3, 4
- ``[0, 5]`` = 0, 1, 2, 3, 4, 5

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(5,5)

### ``randn``

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

In [ ]:
np.random.randn(5,5)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(np.random.rand(5000),bins=40)
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
plt.hist(np.random.randn(500000),bins=1500)
plt.show()

### ``randint``
Return random integers from `low` (inclusive) to `high` (exclusive).

randint(low, high=None, size=None, dtype=int)

In [ ]:
np.random.randint(10)

In [ ]:
np.random.randint(1,101)

In [ ]:
np.random.randint(1,101,10)

In [ ]:
np.random.randint(5,size=(2,4))

In [ ]:
np.random.randint(1,[3,50,100]) # upper band belirleme, her elemana sinir koymak

In [ ]:
np.random.randint(1,[3,50,100]) 

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(36)
rand_arr = np.random.randint(0, 50, 10)

In [ ]:
arr

In [ ]:
rand_arr

### Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.shape

In [ ]:
# arr.reshape(36,1)
arr.reshape(6,6)

In [ ]:
arr.reshape(9,4)


In [ ]:
arr.reshape(3,4,3)

### ``max``, ``min``, ``argmax``, ``argmin``

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [52]:
rand_arr

array([10, 25,  9,  9, 21, 12, 34, 27, 12,  2])

In [53]:
print(rand_arr.max())
print(rand_arr.argmax())
print(rand_arr.min())
print(rand_arr.argmin())

34
6
2
9


## Some other attributes :
* ``shape``: tuple of array dimensions.
* ``size``: Number of elements in the array.
* ``ndim``: number of array dimensions.
* ``itemsize``: the size in bytes of each element of the array.
* ``dtype``: data types of the array.



## ``shape``

Shape is an attribute that arrays have (not a method):

In [54]:
arr.shape

(36,)

## ``dtype``

You can also grab the data type of the object in the array:

In [55]:
arr.dtype

dtype('int32')

## ``ndim``

In [56]:
arr.ndim

1

## ``size``

In [57]:
arr.size

36

# Concatenation of the Arrays

concatenate((a1, a2, ...), axis=0, out=None)

In [58]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [59]:
x

array([1, 2, 3])

In [60]:
y

array([4, 5, 6])

In [61]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [62]:
z = np.array([7,8,9])

In [63]:
np.concatenate([x,y,z]) # limit yok 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.concatenate([x,y,z],axis=1) # axis 1 yok

AxisError: axis 1 is out of bounds for array of dimension 1

In [67]:
x.reshape(1,3)

array([[1, 2, 3]])

In [65]:
np.concatenate([x.reshape(1,3), y.reshape(1,3), z.reshape(1,3)], axis = 0) # 0 eksene ekledi alt alta, 1 olsdaydi yanyana ekleyecekti

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.concatenate([x.reshape(1,3), y.reshape(1,3), z.reshape(1,3)], axis = 1) #1 olsdu yanyana ekledi

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 2d matrix

In [68]:
a = np.random.randint(10, size = (2,3))
b = np.random.randint(10, size = (2,3))

In [72]:
a

array([[4, 9, 1],
       [1, 3, 6]])

In [73]:
b

array([[7, 0, 6],
       [4, 3, 3]])

In [76]:
np.concatenate([a, b]) # axis defaul 0

array([[4, 9, 1],
       [1, 3, 6],
       [7, 0, 6],
       [4, 3, 3]])

In [75]:
np.concatenate([a, b], axis=1)

array([[4, 9, 1, 7, 0, 6],
       [1, 3, 6, 4, 3, 3]])

# Splitting of the Arrays

np.split(ary, indices_or_sections, axis=0)

In [77]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [ ]:
np.split(x, [3, 5])

In [ ]:
a,b,c = np.split(x, [3,5])

In [ ]:
a

### 2d matrix

In [82]:
m = np.arange(20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [83]:
np.vsplit(m,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

array([1, 2, 3])

# Sorting of the Arrays

In [85]:
v = np.array([2,1,4,3,5])
print(v)
np.sort(v)

[2 1 4 3 5]


array([1, 2, 3, 4, 5])

### 2d matrix

In [86]:
twoD = np.random.randint(5,100,(3,3))

twoD

array([[50, 87, 46],
       [49, 75, 71],
       [28, 56, 56]])

In [87]:
np.sort(twoD, axis=0)  # the rows are sorted from upper to lower and column by column |
 #                   | dikey kolonlar arasinda siraliyor

array([[28, 56, 46],
       [49, 75, 56],
       [50, 87, 71]])

In [88]:
np.sort(twoD, axis=1)  # the columns are sorted from left to right and row by row    ---  yatay satirlari siraliyor kendi icinde

array([[46, 50, 87],
       [49, 71, 75],
       [28, 56, 56]])

# The End of the NumPy Session - 1

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___