COPY

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 47
print(arr)
print(x)

[47  2  3  4  5]
[1 2 3 4 5]


VIEW

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
x= arr.view()

arr[0]=47
print(arr)
print(x)

[47  2  3  4  5]
[47  2  3  4  5]


In [3]:

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0]=13
print(arr)
print(x)

[13  2  3  4  5]
[13  2  3  4  5]


BASE

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # orijinal veriye sahip oldugu icin basvuracagi nesne yok bu nedenle None döndürür
print(y.base) # baska bir nesneye referans verdigi icin o nesneyi görüntüler


None
[1 2 3 4 5]
