In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


0-D Arrays

In [3]:
import numpy as np
arr = np.array(47)
print(arr)

47


1-D Arrays

In [7]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


2-D Arrays
These are often used to represent matrix or 2nd order tensors.

In [10]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
for i in arr[0]:
    print(i,end=",")
    # print(i,sep=",")

1,2,3,

3-D Arrays

In [18]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
# arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [21]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=7)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[1 2 3 4]]]]]]]
number of dimensions : 7
