___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<head>
 <center><title>~NumPy | Lektion-2~</title></center>
</head>

# NumPy-Array Indizierung(Indexing) und -in Scheiben schneiden(Slicing)

In dieser Vorlesung werden wir diskutieren, wie man Elemente oder Gruppen von Elementen aus einem Array auswählt.

https://de.myservername.com/python-list-create

https://ichi.pro/de/numpy-basics-cheat-sheet-2021-python-fur-data-science-151477112223872

In [60]:
import numpy as np

## Bracket-Indizierung und -Auswahl
Der einfachste Weg, ein oder mehrere Elemente eines Arrays auszuwählen, sieht sehr ähnlich in Python-Listen aus:

In [61]:
# Beispiel-Array erstellen.
arr = np.arange(0, 5)
arr

array([0, 1, 2, 3, 4])

In [62]:
# Erhalte einen Wert an einem Index
arr, arr[4]

(array([0, 1, 2, 3, 4]), 4)

In [63]:
# Negative Indizierung funktioniert wie in Python-Listen
arr, arr[-1]

(array([0, 1, 2, 3, 4]), 4)

In [64]:
# Werte in einem Bereich erhalten
arr[1:4]

array([1, 2, 3])

In [65]:
# Werte in einem Bereich erhalten
arr, arr[:5]

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [66]:
# arr[Start:Stop:Schritt], ungerade Zahlen
arr, arr[1::2]

(array([0, 1, 2, 3, 4]), array([1, 3]))

In [67]:
# arr[start:stop:step], gerade Zahlen
arr[0::2]

array([0, 2, 4])

## Indizierung eines 2D-Arrays (Matrizen)

-The general format is 
    ``arr_2d[row][col]``oder 
    ``arr_2d[row, col]``. 

-Ich empfehle normalerweise die Komma-Notation aus Gründen der Klarheit.

In [68]:
arr_2D = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
# Indizierungszeilen
arr_2D[0], arr_2D[1], arr_2D[2]

(array([ 5, 10, 15]), array([20, 25, 30]), array([35, 40, 45]))

In [70]:
# Format ist arr_2d[row][col] oder arr_2d[row,col]
# Individuellen Elementwert erhalten
arr_2D[0], arr_2D[0][2]

(array([ 5, 10, 15]), 15)

In [71]:
arr_2D[0], arr_2D[0][0], arr_2D[0][1], arr_2D[0][2]

(array([ 5, 10, 15]), 5, 10, 15)

In [72]:
# 2D-Array-Slicing
# Form (2,2) von der oberen rechten Ecke
arr_2D, arr_2D[0:2, 1:]

(array([[ 5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]]),
 array([[10, 15],
        [25, 30]]))

In [73]:
arr_2D[2], arr_2D[2,:]

(array([35, 40, 45]), array([35, 40, 45]))

In [74]:
# Mittlere Spalte
arr_2D[:, 1]

array([10, 25, 40])

In [75]:
# Die ganz rechte Spalte
arr_2D[:,2]

array([15, 30, 45])

In [76]:
arr_2D[:,2].shape

(3,)

In [77]:
arr_2D[:,2].reshape(1, -1)

array([[15, 30, 45]])

In [78]:
arr_2D[:,2].reshape(1, -1).shape

(1, 3)

In [79]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [80]:
# lass uns 25 to 99 konvertieren
arr_2D[1, 1] = 99
arr_2D

array([[ 5, 10, 15],
       [20, 99, 30],
       [35, 40, 45]])

In [82]:
# Standard-dtyp ist int. Schau dir die Belegung des float-Wertes an.
arr_2D[1][1] = 7.78
arr_2D

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

### Ausgefallene Indizierung

Mit der ausgefallenen Indizierung können Sie ganze Zeilen oder Spalten außerhalb der Reihenfolge auswählen. Um dies zu zeigen, erstellen wir schnell ein numpy-Array:

In [83]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [84]:
v[1], v[3], v[7]

(3, 9, 21)

In [88]:
# Wir können einzelne Elemente anhand ihrer Indizes in einer Liste auswählen.
index_list = [1,3,7]
v[index_list], v[[1,3,7]]

(array([ 3,  9, 21]), array([ 3,  9, 21]))

In [96]:
# Matrix einrichten
arr_2D = np.zeros((10, 10), dtype=int)
arr_2D

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [97]:
arr_2D.shape

(10, 10)

In [98]:
# Length of array
length_arr = arr_2D.shape[0]
length_arr

10

In [99]:
len(arr_2D)

10

In [100]:
arr_2D[0], arr_2D[3]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [102]:
# Array einrichten
for i in range(length_arr):
    arr_2D[i]=i    
arr_2D

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

Ausgefallene Indizierung ermöglicht Folgendes:

In [107]:
# wir können einzelne Zeilen nach Indizes in einer Liste auswählen
arr_2D[[2, 4]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [109]:
arr_2D[2], arr_2D[4]

(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4]))

In [110]:
arr_2D[2, 4]

2

In [112]:
# Ermöglicht in beliebiger Reihenfolge
arr_2D[[6, 4, 2, 7]]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

    irgendein_array[[Zeilenindizes], [Spaltenindizes]]

In [113]:
arr_2D = np.arange(1, 17).reshape(4, 4)
arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [117]:
# Lass uns separate Werte von 5 und 12 wählen.
# Zeile 1 und Spalte 0. Zeile 2 und Spalte 3.
arr_2D, arr_2D[[1, 2], [0, 3]]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([ 5, 12]))

In [118]:
# Diesmal wählen wir separate Werte von 1, 10 und 16
arr_2D, arr_2D[[0, 2, 3], [0, 1, 3]]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([ 1, 10, 16]))

### Zusammen verwenden von "Einfache Indizierung" und "Ausgefallener  Indizierung"

In [121]:
arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [124]:
# Wählen wir 6 und 8, die sich in derselben Zeile befinden (Index 1).
arr_2D, arr_2D[1, [1, 3]]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([6, 8]))

In [126]:
# Wählen wir 2 und 14, die dieselbe Spalte sind (Index 1)
arr_2D[[0, 3], 1]

array([ 2, 14])

### Zusammen verwenden von "Einfache  schneiden" und "Ausgefallener  Indizierung"¶

In [133]:
arr_2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [130]:
# Wählen wir zwei mittlere Spalten aus
arr_2D, arr_2D[:, [1, 2]]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [131]:
# Wählen wir das kleine Quadrat in der Mitte (4 Elemente)# let's select center small square (4 elements)
arr_2D, arr_2D[1:3, [1, 2]]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 6,  7],
        [10, 11]]))

In [134]:
# Erinnere dich, wie normales Schneiden ausgeführt wird
arr_2D, arr_2D[1:3, 1:3]

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[ 6,  7],
        [10, 11]]))

##### Weitere Hilfe zur Indexierung
Das Indizieren einer 2D-Matrix kann anfangs etwas verwirrend sein, insbesondere wenn Sie beginnen, die Schrittgröße hinzuzufügen. Versuchen Sie die Google-Bildersuche mit der NumPy-Indexierung, um nützliche Bilder zu finden.

# Auswahl nach einer Bedingung

Sehen wir uns kurz an, wie Klammern für die Auswahl basierend auf Vergleichsoperatoren verwendet werden.

In [135]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [140]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [141]:
arr[arr < 6]

array([1, 2, 3, 4, 5])

In [142]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [143]:
# and ==> &
arr[(arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [144]:
# Wenn Sie möchten, können Sie if_statement und for_loop verwenden

# Rundfunk

Numpy-Arrays unterscheiden sich von einer normalen Python-Liste aufgrund ihrer Sendefähigkeit:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [145]:
# Wert mit Indexbereich festlegen (Broadcasting)
arr[:5] = 77
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [173]:
a = [0, 2, 4, 6, 8, 10, 12, 14]

In [148]:
# a[0:3] = 100  # Fehler erhöht
# SyntaxError: invalid syntax

In [174]:
a[:3] = [100, 100, 100]

In [171]:
a

[100, 100, 100, 6, 8, 10, 12]

In [175]:
a[4:6] = [100, 100]
a

[100, 100, 100, 6, 100, 100, 12, 14]

In [176]:
a[6:] = [100]
a

[100, 100, 100, 6, 100, 100, 100]

In [181]:
# Array zurücksetzen, wir werden gleich sehen, warum ich zurücksetzen musste
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
# Wichtige Hinweise
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [184]:
# Werte ändern
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Beachten Sie nun, dass die Änderungen auch in unserem ursprünglichen Array auftreten!

In [185]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Daten werden nicht kopiert, es ist eine Ansicht des ursprünglichen Arrays! Das vermeidet Speicherprobleme!

In [186]:
# Um eine Kopie zu erhalten, müssen Sie explizit sein
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [188]:
# Wir können eine Werteliste in einer genauen Dimension zuordnen.
arr_copy[:6] = [0, 1, 2, 3, 4, 5]

In [189]:
arr, arr_copy

(array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

# NumPy-Operationen

## Rechenoperationen

-Sie können ganz einfach Array mit Array-Arithmetik oder Skalar mit Array-Arithmetik ausführen.

In [192]:
arr = np.arange(0, 10)

In [193]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [194]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [195]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [196]:
import warnings
warnings.filterwarnings('ignore')

In [198]:
# Warnung bei Division durch Null, aber kein Fehler!
# Nur durch nan ersetzt
arr, arr / arr

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]))

In [200]:
# Auch Warnung, aber kein Fehler, sondern unendlich
arr, 1/arr

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
        0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111]))

In [201]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [202]:
v=np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [203]:
v-2

array([-1,  0,  1,  2,  3])

In [204]:
v*10

array([10, 20, 30, 40, 50])

In [205]:
v*5 / 10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

## Universal-Array-Funktionen

-Numpy enthält viele universelle Array-Funktionen, die im Wesentlichen nur mathematische Operationen sind, mit denen Sie die Operation im gesamten Array ausführen können.

http://docs.scipy.org/doc/numpy/reference/ufuncs.html

-Lassen Sie uns einige gängige zeigen:

In [206]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
# Quadratwurzeln ziehen
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [208]:
# Berechnung der Exponentialfunktion (e~)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [209]:
# wie arr.max()
np.max(arr)

9

In [210]:
# Es gibt viele trigonometrische Funktionen
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [211]:
np.sin(np.pi/2)

1.0

In [212]:
np.tan(np.pi/4)

0.9999999999999999

In [213]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [214]:
np.log10(1000)

3.0

In [215]:
v

array([1, 2, 3, 4, 5])

In [216]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [220]:
x1 = np.arange(9.0).reshape(3,3)
x2 = np.arange(3.0)

In [221]:
x1, x2

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [222]:
np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [223]:
np.add(v, 2)

array([3, 4, 5, 6, 7])

In [224]:
np.divide(v, 2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [225]:
np.multiply(v, 4)

array([ 4,  8, 12, 16, 20])

In [227]:
# v**2
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [229]:
# v % 2
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [230]:
np.absolute(np.array([-9]))

array([9])

## Statistische Berechnungen

In [232]:
v = np.array([1, 1, 2, 2, 3, 3, 3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [233]:
np.mean(v)

2.142857142857143

In [234]:
np.median(v)

2.0

In [235]:
v.sum()

15

In [236]:
v.min()

1

``np.mean(arr, axis=0)`` bedeuten entlang einer bestimmten Achse

``arr.sum()`` gibt die Summe von arr zurück

``arr.min()``  gibt den Mindestwert von arr zurück

``arr.max(axis=0)`` gibt den maximalen Wert einer bestimmten Achse zurück

``np.var(arr)`` gibt die Varianz des Arrays zurück

``np.std(arr, axis=1)`` gibt die Standardabweichung einer bestimmten Achse zurück

``arr.corrcoef()``| gibt den Korrelationskoeffizienten von Array zurück

<head>
  <center><title>~Das Ende der NumPy | Lektion-2~</title></center>
</head>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

Sie können sich ein attraktives offizielles Tutorial für Anfänger von NumPy ansehen.
https://numpy.org/devdocs/user/absolute_beginners.html