In [1]:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


In [3]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


Convert Degrees Into Radians

 radians values are pi/180 * degree_values.

In [4]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


Radians to Degrees

In [5]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


Finding Angles

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

Açıları Bulma
Sinüs, cos, tan değerlerinden açıları bulma. Örneğin sin, cos ve tan tersi (arcsin, arccos, arctan).

NumPy ufuncs içerir arcsin(), arccos()ve arctan()belirli bir sin, cos ve tan karşılık gelen değerleri için radyan değerleri üretirler.

In [8]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [9]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


Hypotenues

In [10]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
