A random distribution is a set of random numbers that follow a certain probability density function.

Probability Density Function: A function that describes a continuous probability. i.e. probability of all values in an array.

Olasılık Yoğunluk Fonksiyonu: Sürekli bir olasılığı tanımlayan fonksiyon. yani bir dizideki tüm değerlerin olasılığı.

Her değerin 3, 5, 7 veya 9 olması gereken 100 değer içeren 1 boyutlu bir dizi oluşturun.

Değerin 3 olma olasılığı 0,1 olarak ayarlanmıştır.

Değerin 5 olma olasılığı 0,3 olarak ayarlanmıştır.

Değerin 7 olma olasılığı 0,6 olarak ayarlanmıştır.

Değerin 9 olma olasılığı 0 olarak ayarlanmıştır.

In [1]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

# Tüm olasılık sayılarının toplamı 1 olmalıdır.

[7 5 5 7 7 7 3 3 5 5 7 7 7 7 7 3 7 5 7 7 7 5 5 7 3 5 7 5 7 5 5 7 5 7 7 5 5
 7 7 7 5 5 7 7 7 7 7 5 7 7 7 5 7 7 7 3 5 5 7 7 7 5 7 3 7 5 7 5 7 5 7 7 7 3
 5 7 5 7 5 7 7 7 7 7 7 7 5 7 7 5 7 7 5 3 7 7 7 5 7 5]


In [2]:
from numpy import random
x= random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size = (3, 5))
print(x)

[[7 7 7 5 7]
 [7 5 7 7 5]
 [5 7 7 5 5]]
