___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2 (Part - 2)</p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [3]:
import numpy as np

In [5]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [6]:
arr[8]

8

In [11]:
arr[-1]

10

In [12]:
type(arr[3])

numpy.int32

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[1:5]

[1 2 3 4]


In [14]:
arr[1:2]

array([1])

In [15]:
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [16]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d[1]

array([20, 25, 30])

In [20]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[1,2:]

array([30])

In [26]:
arr_2d[1,2]

30

In [27]:
arr_2d[1][2]

30

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d[2]

array([35, 40, 45])

In [31]:
arr_2d[2,:]

array([35, 40, 45])

In [33]:
arr_2d[:,1]

array([10, 25, 40])

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[1,1]

25

In [36]:
arr_2d[1,1]=99
arr_2d

array([[ 5, 10, 15],
       [20, 99, 30],
       [35, 40, 45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [38]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [39]:
v[1]

3

In [40]:
v[3]

9

In [41]:
v[7]

21

In [45]:
index_liste=[1,3,7]
# index_liste=[True,False,True,True,False,True,True,False,True,True]
v[index_liste]

array([ 3,  9, 21])

In [46]:
arr2d=np.zeros((10,10),dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
arr2d.shape

(10, 10)

In [48]:
arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
for i in range(10):
    arr2d[i]=i
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [49]:
ar_list=range(10)

In [69]:
arr2d=np.zeros((10,10),dtype=int)
ar_list=range(10)
arr2d[:] = ar_list[:]
arr2d.T

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [55]:
arr2d[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [57]:
k = [6,4,2,7]

In [58]:
arr2d[k]

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

<h3>any_array[[row indices], [column indices]]</h3>

In [62]:
jj=np.arange(1,17).reshape(4,4)
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [64]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [66]:
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

### Using ***basic index*** and ***fancy index*** together

In [67]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
jj[1,[1,3]]

array([6, 8])

In [71]:
jj[[0,3],1]

array([ 2, 14])

### Using ***basic slicing*** and ***fancy index*** together

In [72]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [73]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [74]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [76]:
arr= np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
bool_arr=arr>4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [80]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
arr[(arr!=3)& (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [83]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
arr[:5] = 77
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [88]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [105]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr_copy=arr.copy()
arr_copy


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr_copy[:6]=[0,1,2,3,4,5]
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [107]:
import numpy as np
arr = np.arange(0,10)

In [108]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [109]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [110]:
arr/arr

C:\Users\bulen\AppData\Local\Temp/ipykernel_14048/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [111]:
arr/0

C:\Users\bulen\AppData\Local\Temp/ipykernel_14048/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
C:\Users\bulen\AppData\Local\Temp/ipykernel_14048/4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [112]:
1/arr

C:\Users\bulen\AppData\Local\Temp/ipykernel_14048/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [113]:
import warnings
warnings.filterwarnings('ignore')

In [114]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [115]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [116]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [117]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [119]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [120]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [122]:
np.sin(np.pi/2)

1.0

In [123]:
np.max(arr)

9

In [124]:
np.amax(arr)

9

In [125]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [126]:
np.log10(1000)

3.0

In [127]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [128]:
np.subtract(v,1)

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [130]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [131]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.subtract(v,arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [132]:
v**2

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729], dtype=int32)

In [134]:
np.power(v,2)

array([  0,   9,  36,  81, 144, 225, 324, 441, 576, 729], dtype=int32)

## Statistical Calculations

In [135]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [136]:
np.mean(v)

2.142857142857143

In [137]:
np.median(v)

2.0

In [150]:
from scipy import stats
stats.mode(v)

ModeResult(mode=array([3]), count=array([3]))

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``arr.corrcoef()`` | Returns correlation coefficient of array

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.