___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 1</p><h1>

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [9]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [6]:
type(my_list)

list

In [10]:
my_array=np.array(my_list)
my_array


array([1, 2, 3])

In [11]:
type(my_array)

numpy.ndarray

### Why NumPy?

In [13]:
#liste 
a= [1,2,3,4]
b= [1,2,3,4]

In [14]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [19]:
a*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
ab=[]
for i in range(len(a)):
    ab.append(a[i]*b[i])
print(ab)

[1, 4, 9, 16]


In [16]:
a1 = np.array([[1,2,3,4],[1,2,3,4],[2,3,4,5]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [17]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

In [18]:
a1*3

array([[ 3,  6,  9, 12],
       [ 3,  6,  9, 12],
       [ 6,  9, 12, 15]])

In [20]:
a1.ndim # boyutlari verir dimension

2

In [21]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
# ic ice liste

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
type(my_matrix)

list

In [22]:
new_matrix = np.array(my_matrix)
new_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
type(new_matrix)

numpy.ndarray

### Built-in Methods

There are lots of built-in ways to generate Arrays

### ``arange``

Return evenly spaced values within a given interval.

arange([start,] stop[, step,], dtype=None)

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.arange(0,11,1.5)

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5])

In [29]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

### ``linspace``
Return evenly spaced numbers over a specified interval.

np.linspace(start, stop, num=50)

In [31]:
np.linspace(0,10) # hic yazmazsak number 50 dir 50 tane yazar

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [33]:
np.linspace(0,10, num=9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [34]:
np.linspace(0,10, num=20, dtype=int)

array([ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
        8,  9, 10])

In [39]:
set(np.linspace(0, 10, 51, dtype = "int"))
# np.linspace(0, 10, 50, dtype = "int")

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

### **``zeros``, ``ones`` and ``full``**

Generate arrays of zeros or ones

np.zeros(shape, dtype=float, order='C')

np.ones(shape, dtype=None, order='C')

np.full(shape, fill_value, dtype=None, order='C')

In [41]:
np.zeros(3) # 0 elemanli float array üretir

array([0., 0., 0.])

In [42]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
np.ones(3)

array([1., 1., 1.])

In [46]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [48]:
x=np.ones((4,4),dtype=str)
x

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [50]:
type(x)

numpy.ndarray

In [53]:
np.ones((4,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
np.zeros((4,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [56]:
np.full((3, 5), "3", order = "C") 

# "C" C language "F" fortran language
# Whether to store multidimensional data in C- or Fortran-contiguous 
# (row- or column-wise) order in memory.

array([['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3'],
       ['3', '3', '3', '3', '3']], dtype='<U1')

### ``eye``

Creates an [identity matrix](https://www.mathbootcamps.com/the-identity-matrix-and-its-properties/)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random 

Numpy also has lots of ways to create random number arrays:

### ``rand``
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

- ``(0, 5)`` = 1, 2, 3, 4
- ``(0, 5]`` = 1, 2, 3, 4, 5
- ``[0, 5)`` = 0, 1, 2, 3, 4
- ``[0, 5]`` = 0, 1, 2, 3, 4, 5

In [62]:
np.random.rand(2)

array([0.34376243, 0.81110438])

In [83]:
np.random.rand(5,5)

array([[0.36971207, 0.26626736, 0.74491027, 0.79331285, 0.11435885],
       [0.10809094, 0.76624524, 0.50896562, 0.81597127, 0.67251368],
       [0.44113743, 0.03194813, 0.85087779, 0.32573407, 0.1222458 ],
       [0.34554411, 0.22539667, 0.41408844, 0.29248727, 0.82551217],
       [0.9302932 , 0.08966267, 0.96811314, 0.49694157, 0.97208692]])

### ``randn``

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

### ``randint``
Return random integers from `low` (inclusive) to `high` (exclusive).

randint(low, high=None, size=None, dtype=int)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

### Reshape
Returns an array containing the same data with a new shape.

### ``max``, ``min``, ``argmax``, ``argmin``

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

## Some other attributes :
* ``shape``: tuple of array dimensions.
* ``size``: Number of elements in the array.
* ``ndim``: number of array dimensions.
* ``itemsize``: the size in bytes of each element of the array.
* ``dtype``: data types of the array.



## ``shape``

Shape is an attribute that arrays have (not a method):

## ``dtype``

You can also grab the data type of the object in the array:

## ``ndim``

## ``size``

# Concatenation of the Arrays

concatenate((a1, a2, ...), axis=0, out=None)

### 2d matrix

# Splitting of the Arrays

np.split(ary, indices_or_sections, axis=0)

### 2d matrix

# Sorting of the Arrays

### 2d matrix

# The End of the NumPy Session - 1

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___