In [1]:
import numpy as np


In [3]:
a= np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[:3]

array([20, 21, 22])

In [5]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [11]:
a= np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a[2,1]

8

In [13]:
a[:,1]

array([2, 5, 8])

In [21]:
b= np.arange(10,30).reshape(4,5)
b[1:,2:4]

array([[17, 18],
       [22, 23],
       [27, 28]])

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
x= np.arange(20,30)
x[:3]=5
x

array([ 5,  5,  5, 23, 24, 25, 26, 27, 28, 29])

In [26]:
# liste
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
l[:3]=[100,100,100]
l

[100, 100, 100, 3, 4, 5, 6, 7, 8, 9]

In [29]:
x

array([ 5,  5,  5, 23, 24, 25, 26, 27, 28, 29])

In [34]:
arr = np.arange(20,30)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
a_slice=arr[:3]
a_slice

array([5, 5, 5])

In [33]:
arr

array([ 5,  5,  5, 23, 24, 25, 26, 27, 28, 29])

In [36]:
a_copy=arr.copy()
a_slice=a_copy[:5]
a_slice[:3]=5
a_slice

array([ 5,  5,  5, 23, 24])

In [40]:
a= np.random.randint(1,100,15)
a

array([18, 66,  8, 65,  2, 61, 10, 62, 87,  3, 15, 39, 90, 27, 63])

In [41]:
a<50

array([ True, False,  True, False,  True, False,  True, False, False,
        True,  True,  True, False,  True, False])

In [62]:
a= np.random.randint(1,100,15)
print(a[a<50])
print(len(a[a<50]))
b=a[a<50]
b

[32 36 44  8 16 40]
6


array([32, 36, 44,  8, 16, 40])

In [72]:
a[(a<25)|(a>75)]

array([78,  8, 16, 77, 80, 84])

In [73]:
a[(a>25)&(a<75)]

array([53, 63, 32, 36, 44, 70, 40, 52, 54])