In [1]:
import numpy as np
a = np.arange(3,12).reshape(3,3)
b = np.eye(3,3)
print(a)
print(b)
np.matmul(a,b)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])