Summations
What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.



In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
arr3 = np.array([1, 1, 1])

newarr = np.sum([arr1, arr2, arr3])

print(newarr)

15


Summation Over an Axis

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
arr3 = np.array([1, 1, 1])

newarr = np.sum([arr1, arr2, arr3], axis=1)

print(newarr)

[6 6 3]


Cummulative Sum

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([0,1,2,3,4])
newarr1 = np.cumsum(arr1)
newarr2 = np.cumsum(arr2)
print(newarr1)
print(newarr2)

[1 3 6]
[ 0  1  3  6 10]
