In [1]:
# Generate a random integer from 0 to 100:

from numpy import random
x = random.randint(100)
print(x)

12


In [10]:
from numpy import random
x=[]
for i in range(100):
    x.append(random.randint(100))
s = set(x)
print(len(x))
print(len(s))

100
64


In [2]:
# Generate Random Float

In [11]:
# Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x)

0.6148473762023409


Generate Random Array

In [12]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x)

[55  1 90 24 35]


In [14]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[75 53 77 46 27]
 [41 37 46 17 54]
 [82  7 21 60 87]]


In [16]:
from numpy import random

x = random.randint(2, size=(3, 5))

print(x)

[[1 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [17]:
from numpy import random

x = random.randint(2, size=(3,3))

print(x)

[[1 0 1]
 [0 1 1]
 [1 0 0]]


Floats

In [18]:
from numpy import random

x = random.rand(5)

print(x)

[0.48004873 0.38377877 0.1886616  0.21507764 0.23167738]


In [19]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:

from numpy import random

x = random.rand(3, 5)

print(x)

[[0.7671103  0.9124265  0.75090635 0.54881576 0.91038271]
 [0.22282861 0.00800939 0.34620972 0.41950953 0.35906869]
 [0.03324053 0.38022064 0.69851161 0.36158303 0.06004325]]


Generate Random Number From Array

In [24]:
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

7


In [28]:
from numpy import random
shuffle_list=[]
for i in range(10):
    shuffle_list.append(random.choice([1,2,3,4,5,6,7,8,9]))
print(shuffle_list)

[6, 2, 7, 2, 9, 7, 9, 2, 8, 5]


In [29]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 3 5 9 3]
 [5 9 7 9 5]
 [7 3 7 3 9]]
