In [1]:
# Randomly shuffle elements of following array:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[4 2 3 1 5]


In [8]:
from numpy import random
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
random.shuffle(arr)

print(arr)

[8 4 3 9 6 0 2 5 7 1]


Generating Permutation of Arrays

In [10]:
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))
print(arr)

[3 4 2 1 5]
[1 2 3 4 5]
