In [9]:
import numpy as np
a = np.arange(3,12).reshape(3,3)
b = np.eye(3,3)
print(a)
print(b)
np.matmul(a,b)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [10]:
data = np.arange(1,27,3).reshape(3,3)
data

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [11]:
np.sum(data[:,1])

39

In [12]:
np.mean(data[:,2])

16.0

In [13]:
np.median(data[1,:])

13.0

In [27]:
random_data=(np.random.rand(16)*10).reshape(8,2)
print(random_data)
st_1 = np.std(random_data[:,0]) # 1. sütunun sdtandart sapmasi
print("1. sütunun sdtandart sapmasi: ",st_1)
st_2 = np.corrcoef(random_data[:,0],random_data[:,1])
# print("1. ve 2 sütunlarin corelasyon katsayisi: ",st_2)
print("1. ve 2 sütunlarin corelasyon katsayisi: ",st_2[0][1])



[[0.76086579 1.95509632]
 [5.7073057  2.4349138 ]
 [4.59500442 3.17493909]
 [9.81269729 0.69350349]
 [8.1212643  4.94803137]
 [0.41339759 7.71797479]
 [5.51063647 0.49450654]
 [8.78274683 5.42731117]]
1. sütunun sdtandart sapmasi:  3.2678524297679266
1. ve 2 sütunlarin corelasyon katsayisi:  [[ 1.         -0.26294109]
 [-0.26294109  1.        ]]
1. ve 2 sütunlarin corelasyon katsayisi:  -0.2629410935399321


In [28]:
random_data

array([[0.76086579, 1.95509632],
       [5.7073057 , 2.4349138 ],
       [4.59500442, 3.17493909],
       [9.81269729, 0.69350349],
       [8.1212643 , 4.94803137],
       [0.41339759, 7.71797479],
       [5.51063647, 0.49450654],
       [8.78274683, 5.42731117]])

In [29]:
for i in random_data:
    print(i)

[0.76086579 1.95509632]
[5.7073057 2.4349138]
[4.59500442 3.17493909]
[9.81269729 0.69350349]
[8.1212643  4.94803137]
[0.41339759 7.71797479]
[5.51063647 0.49450654]
[8.78274683 5.42731117]


In [34]:
for i in np.nditer(random_data,order='C'): # satir satir siraliyor
    print(i)

0.7608657931269269
1.9550963209740835
5.707305697164669
2.434913799322392
4.595004422387186
3.1749390853965354
9.812697286987051
0.693503488389825
8.121264302716838
4.948031370458933
0.4133975930367617
7.717974787289181
5.5106364726049275
0.49450654007766826
8.782746832731785
5.427311174660726


In [35]:
for i in np.nditer(random_data,order='F'): # sütun sütun siraliyor
    print(i)

0.7608657931269269
5.707305697164669
4.595004422387186
9.812697286987051
8.121264302716838
0.4133975930367617
5.5106364726049275
8.782746832731785
1.9550963209740835
2.434913799322392
3.1749390853965354
0.693503488389825
4.948031370458933
7.717974787289181
0.49450654007766826
5.427311174660726


In [46]:
x_data = np.random.uniform(low=1, high=50, size=16).round(3).reshape(4,4)
x_data


array([[28.419, 32.873, 17.93 , 35.742],
       [11.327, 14.279, 43.665,  7.345],
       [17.264, 12.329,  1.678,  5.608],
       [ 1.371, 43.984,  5.331, 27.556]])

In [47]:
print(np.amax(x_data,axis=0))
print(np.amax(x_data,axis=1))

[28.419 43.984 43.665 35.742]
[35.742 43.665 17.264 43.984]


In [48]:
np.argsort(x_data)

array([[2, 0, 1, 3],
       [3, 0, 1, 2],
       [2, 3, 1, 0],
       [0, 2, 3, 1]], dtype=int64)

In [51]:
import numpy as np

Score_arr = np.array([500, 600, 300, 400, 700, 100, 200])

Sorted_Score_arr = np.argsort(Score_arr)
print(Score_arr)
print(Sorted_Score_arr)

[500 600 300 400 700 100 200]
[5 6 2 3 0 1 4]
