In [2]:
import numpy as np
exam_1= [23,24,54,42,36,78,95,73,89,100]
exam_2= [33,44,43,25,66,83,56,38,98,100]

exam_1_array = np.array(exam_1)
exam_2_array = np.array(exam_2)
exam_av_array= exam_1_array/2+exam_2_array/2
print(exam_1)
print(exam_2)
print(exam_av_array)
print(exam_av_array[exam_av_array>49])
print(np.average(exam_av_array[exam_av_array>49]))
print(np.average(exam_av_array))

[23, 24, 54, 42, 36, 78, 95, 73, 89, 100]
[33, 44, 43, 25, 66, 83, 56, 38, 98, 100]
[ 28.   34.   48.5  33.5  51.   80.5  75.5  55.5  93.5 100. ]
[ 51.   80.5  75.5  55.5  93.5 100. ]
76.0
60.0


In [9]:
arr= np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
matrix = arr.reshape(4,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
matrix[2:3,3:4]
matrix[2,3]
matrix[2:,3:]
matrix[:2,:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [16]:
exam_av_array.clip(40,70)

array([40. , 40. , 48.5, 40. , 51. , 70. , 70. , 55.5, 70. , 70. ])

In [20]:
print(exam_av_array)
exam_av_array.round(0)

[ 28.   34.   48.5  33.5  51.   80.5  75.5  55.5  93.5 100. ]


array([ 28.,  34.,  48.,  34.,  51.,  80.,  76.,  56.,  94., 100.])

In [24]:
ar_2=np.arange(1,10).reshape(3,3)
ar_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
ar_2.trace()

15

In [31]:
l = [10,20,30,40,50,20,30,40,80]
ar_3=np.array(l)
print(ar_3.reshape(3,3))
print(ar_3.reshape(3,3).trace())


[[10 20 30]
 [40 50 20]
 [30 40 80]]
140


In [34]:
a_1 = np.arange(1,11)
a_2 = np.arange(11,21)
print(a_1)
print(a_2)
np.prod(a_1)  # dizideki sayilari carpar

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


3628800

In [68]:
q = np.random.randint(10,size=(3,3))
q

array([[3, 8, 3],
       [7, 6, 4],
       [7, 0, 2]])

In [62]:
q.sort()
q

array([[0, 3, 9],
       [1, 2, 8],
       [0, 7, 8]])

In [69]:
q.sort(axis=0)
q

array([[3, 0, 2],
       [7, 6, 3],
       [7, 8, 4]])

In [70]:
np.sort(q,axis=1)

array([[0, 2, 3],
       [3, 6, 7],
       [4, 7, 8]])