___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Series, Session - 3</p><h1>

## Creating a Pandas Series

In [1]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [2]:
np.array([1,2,3, 1.1])

array([1. , 2. , 3. , 1.1])

In [3]:
pd.Series([2,3,4,5])

0    2
1    3
2    4
3    5
dtype: int64

In [5]:
ser = pd.Series([2,3,4,5])

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [8]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [9]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [10]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

### **Using NumPy Arrays**

In [12]:
pd.Series(data=arr,index=labels)

a    10
b    20
c    30
dtype: int32

### **Using Dictionary**

In [13]:
d

{'a': 10, 'b': 20, 'c': 30}

In [14]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [15]:
pd.Series(data=d,index=['q','c','y'])

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [16]:
pd.Series(data="steve")

0    steve
dtype: object

In [18]:
pd.Series(data="steve", index = range(3))

0    steve
1    steve
2    steve
dtype: object

In [19]:
pd.Series(data=10, index = ['a','b','c'])

a    10
b    10
c    10
dtype: int64

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [26]:
tup1 = (1,2,3,4,4)
tup1

(1, 2, 3, 4, 4)

In [27]:
pd.Series(data=tup1)

0    1
1    2
2    3
3    4
4    4
dtype: int64

In [29]:
pd.Series(int)

0    <class 'int'>
dtype: object

In [30]:
pd.Series(list)

0    <class 'list'>
dtype: object

In [31]:
pd.Series([set,list,len])

0              <class 'set'>
1             <class 'list'>
2    <built-in function len>
dtype: object

In [33]:
pd.Series([set,list,len])[0]

set

In [36]:
a = {1,2,3,4,5,5}
a
pd.Series(a)

TypeError: 'set' type is unordered

In [37]:
pd.Series([set,list,len])[0]

set

In [38]:
pd.Series([set,list,len])[2]("Martin")

6

In [39]:
pd.Series([set,print("ali"),len])[2]

ali


<function len(obj, /)>

In [40]:
pd.Series([set,print("ali"),len])

ali


0              <class 'set'>
1                       None
2    <built-in function len>
dtype: object

In [41]:
mix_data= ['Steve',2,True]
mix_data

['Steve', 2, True]

In [42]:
pd.Series(mix_data)

0    Steve
1        2
2     True
dtype: object

In [44]:
pd.Series(mix_data)[2]

True

In [45]:
np.array(mix_data)

array(['Steve', '2', 'True'], dtype='<U11')

In [46]:
print(np.array(mix_data))

['Steve' '2' 'True']


## Basic Attributes of Series

In [47]:
ser

0    2
1    3
2    4
3    5
dtype: int64

In [48]:
type(ser)

pandas.core.series.Series

In [49]:
ser.dtype

dtype('int64')

In [50]:
ser.shape

(4,)

In [51]:
ser.ndim

1

In [52]:
ser.size

4

In [53]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [64]:
ser.keys()

RangeIndex(start=0, stop=4, step=1)

In [57]:
ser.values

array([2, 3, 4, 5], dtype=int64)

In [58]:
ser.item

<bound method IndexOpsMixin.item of 0    2
1    3
2    4
3    5
dtype: int64>

In [59]:
for i in ser.values:
    print(i)

2
3
4
5


In [60]:
[i for i in ser.values]

[2, 3, 4, 5]

In [71]:
ser.items()

In [72]:
ser.items

<bound method Series.items of 0    2
1    3
2    4
3    5
dtype: int64>

In [66]:
list(ser.items())

[(0, 2), (1, 3), (2, 4), (3, 5)]

In [69]:
print(* ser.items())

(0, 2) (1, 3) (2, 4) (3, 5)


In [70]:
for index,value in ser.items():
    print(index,value)

0 2
1 3
2 4
3 5


In [75]:
ser = pd.Series(data = np.random.randint(0,25,10),\
                index = [i for i in "cbaefdgihj"])
ser


c     4
b    10
a    11
e     5
f     1
d    18
g    15
i    12
h     7
j     5
dtype: int32

In [76]:
ser.head()

c     4
b    10
a    11
e     5
f     1
dtype: int32

In [79]:
ser.tail()

d    18
g    15
i    12
h     7
j     5
dtype: int32

In [82]:
ser.sample()

b    10
dtype: int32

In [83]:
ser.sample(3)

h     7
i    12
g    15
dtype: int32

In [86]:
ser.sort_index()

a    11
b    10
c     4
d    18
e     5
f     1
g    15
h     7
i    12
j     5
dtype: int32

In [88]:
ser.sort_index(ascending=True)

a    11
b    10
c     4
d    18
e     5
f     1
g    15
h     7
i    12
j     5
dtype: int32

In [89]:
ser.sort_index()

f     1
c     4
e     5
j     5
h     7
b    10
a    11
i    12
g    15
d    18
dtype: int32

In [91]:
ser.sort_values(ascending=False)

d    18
g    15
i    12
a    11
b    10
h     7
e     5
j     5
c     4
f     1
dtype: int32

In [93]:
ser.isin([5])

c    False
b    False
a    False
e     True
f    False
d    False
g    False
i    False
h    False
j     True
dtype: bool

In [94]:
ser.isin([5,12])

c    False
b    False
a    False
e     True
f    False
d    False
g    False
i     True
h    False
j     True
dtype: bool

In [95]:
[i for i in "clarusway"]

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [96]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [99]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])

In [98]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [100]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [101]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [103]:
ser1.sort_index()

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [105]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [106]:
ser1[0]

1

In [107]:
ser1['Germany']

2

In [108]:
ser1.Germany

2

In [110]:
ser1[ser1>2]

USSR     3
Japan    4
dtype: int64

In [112]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])

In [114]:
ser3

0    a
1    b
2    c
3    d
dtype: object

In [113]:
ser3[0]

'a'

In [115]:
ser3[2:]

2    c
3    d
dtype: object

In [117]:
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [119]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "noah"])
panser

terry      121
micheal    200
orion      150
noah        99
dtype: int64

In [120]:
panser.index

Index(['terry', 'micheal', 'orion', 'noah'], dtype='object')

In [121]:
panser[0]

121

In [122]:
panser['terry']

121

In [124]:
panser['terry':'noah']

terry      121
micheal    200
orion      150
noah        99
dtype: int64

In [125]:
panser[0:3]

terry      121
micheal    200
orion      150
dtype: int64

<h1><p style="text-align: center;">Pandas DataFrames, Session - 3</p><h1>

In [126]:
data=[1, 2, 39, 67, 90]
data

[1, 2, 39, 67, 90]

In [127]:
# np.array
# pd.Series
pd.DataFrame(data, columns=['Column_1'])

Column_1
0         1
1         2
2        39
3        67
4        90

In [129]:
data2 =np.arange(1, 10).reshape(3,3)
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
pd.DataFrame(data2)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [135]:
pd.DataFrame(data2, columns=['var1', 'var2','var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [139]:
data3=np.arange(1,101).reshape(25,4)
data3

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [143]:
df3= pd.DataFrame(data3, columns=['var1', 'var2','var3','var4'])
df3

var1  var2  var3  var4
0      1     2     3     4
1      5     6     7     8
2      9    10    11    12
3     13    14    15    16
4     17    18    19    20
5     21    22    23    24
6     25    26    27    28
7     29    30    31    32
8     33    34    35    36
9     37    38    39    40
10    41    42    43    44
11    45    46    47    48
12    49    50    51    52
13    53    54    55    56
14    57    58    59    60
15    61    62    63    64
16    65    66    67    68
17    69    70    71    72
18    73    74    75    76
19    77    78    79    80
20    81    82    83    84
21    85    86    87    88
22    89    90    91    92
23    93    94    95    96
24    97    98    99   100

In [144]:
df3.head()

var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16
4    17    18    19    20

In [146]:
df3.tail(6)

var1  var2  var3  var4
19    77    78    79    80
20    81    82    83    84
21    85    86    87    88
22    89    90    91    92
23    93    94    95    96
24    97    98    99   100

In [148]:
df3.sample()

var1  var2  var3  var4
20    81    82    83    84

In [149]:
df3.sample(3)

var1  var2  var3  var4
14    57    58    59    60
16    65    66    67    68
9     37    38    39    40

In [151]:
df3.columns

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [152]:
for i in df3.columns:
    print(i)

var1
var2
var3
var4


In [155]:
a=list(df3.columns)
a

['var1', 'var2', 'var3', 'var4']

In [160]:
df3["var3"]

0      3
1      7
2     11
3     15
4     19
5     23
6     27
7     31
8     35
9     39
10    43
11    47
12    51
13    55
14    59
15    63
16    67
17    71
18    75
19    79
20    83
21    87
22    91
23    95
24    99
Name: var3, dtype: int32

In [161]:
df3[["var3"]]

var3
0      3
1      7
2     11
3     15
4     19
5     23
6     27
7     31
8     35
9     39
10    43
11    47
12    51
13    55
14    59
15    63
16    67
17    71
18    75
19    79
20    83
21    87
22    91
23    95
24    99

In [163]:
df3.head()

var1  var2  var3  var4
0     1     2     3     4
1     5     6     7     8
2     9    10    11    12
3    13    14    15    16
4    17    18    19    20

In [164]:
df3.shape

(25, 4)

In [165]:
df3.size # toplam eleman sayisi

100

In [167]:
len(df3) # satir sayisi, row

25

In [178]:
new_df=pd.read_csv("data.csv",encoding ='unicode_escape')
new_df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

            InvoiceDate  UnitPrice  CustomerID         Country  
0        12/1/2010 8:26       2.55     17850.0  United Kingdom  
1        12/1/2010 8:26       3.39     17850.0  United Kingdom  
2        12/1/2010 8:26       2.75     17850.0  United Kingdom  
3        12/1/2010 8:26       3.39     17850.0  United Kingdom  
4        12/1/2010 8:26       3.39     17850.0  United Kingdom  
...                 ...        ...         ...             ...  
541904  12/9/2011 12:50       0.85     12680.0          France  
541905  12/9/2011 12:50       2.10     12680.0          France  
541906  12/9/2011 12:50       4.15     12680.0          France  
541907  12/9/2011 12:50       4.15     12680.0          France  
541908  12/9/2011 12:50       4.95     12680.0          France  

[541909 rows x 8 columns]

### Recap for Several Selecting Attributes

In [182]:
panser

terry      121
micheal    200
orion      150
noah        99
dtype: int64

In [183]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'noah'], dtype='object')

In [185]:
panser.index

Index(['terry', 'micheal', 'orion', 'noah'], dtype='object')

In [192]:
# ['terry'] in panser

In [191]:
panser.isin(['terry'])

terry      False
micheal    False
orion      False
noah       False
dtype: bool

In [193]:
panser

terry      121
micheal    200
orion      150
noah        99
dtype: int64

In [194]:
panser['terry'] =90

In [195]:
panser

terry       90
micheal    200
orion      150
noah        99
dtype: int64

In [199]:
panser[panser<100]
panser

terry      90
micheal    90
orion      90
noah       90
dtype: int64

In [200]:
panser<100

terry      True
micheal    True
orion      True
noah       True
dtype: bool

In [198]:
panser.index.isin(['terry'])

array([ True, False, False, False])

for your info:

* 1 dim --> vector 
* 2 dim --> matrix
* 3 dim --> tensor