Reshape From 1-D to 2-D

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np

arr = np.array([1, 1, 1, 0, 0, 0, 0, 0, 0 ])

newarr = arr.reshape(3, 3)

print(newarr)

[[1 1 1]
 [0 0 0]
 [0 0 0]]


Reshape From 1-D to 3-D

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
try:
    newarr = arr.reshape(3, 3)
    print(newarr)
except Exception as e:
    print(e)


cannot reshape array of size 8 into shape (3,3)


Returns Copy or View?

The example above returns the original array, so it is a view.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
print(arr.reshape(2, 4))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this.

In [10]:
#Convert the array into a 1D array:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
