In [3]:
import numpy as np
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


In [5]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [6]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Sorting a 2-D Array

In [7]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
