If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [1]:
import numpy as np
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [3]:
import numpy as np
arr = np.array([41,42,43,44])
filter=[True, False, True, True]#
newarray=arr[filter]
print(newarray)
print(arr)


[41 43 44]
[41 42 43 44]


Creating the Filter Array

In [4]:
import numpy as np
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
filter_arr=[]
for i in arr:
    if i % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_arr=arr[filter_arr]
print(new_arr)
print(arr)


[2 4 6 8]
[1 2 3 4 5 6 7 8 9]


Creating Filter Directly From Array

In [8]:
import numpy as np
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [9]:
import numpy as np

arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [11]:
import numpy as np

arr = np.array([41, 42, 43, 44])
newarr = arr[ arr > 42]
print(newarr)

[43 44]


In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False  True False  True False  True False]
[2 4 6]
