In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
for string in arr:
    print(string)

b'1'
b'2'
b'3'
b'4'


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [6]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [7]:
import numpy as np
try:
    arr = np.array(['a', '2', '3'], dtype='i')
except Exception as e:
    print(e)


invalid literal for int() with base 10: 'a'


Converting Data Type on Existing Arrays

In [13]:
import numpy as np
arr = np.array([1.1, 2.1, 3.7])
newarr = arr.astype('i')
print (arr)
print(newarr)

print(newarr.dtype)


[1.1 2.1 3.7]
[1 2 3]
int32


In [11]:
import numpy as np

arr = np.array([1.1, 2.1, 3.7])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [15]:
import numpy as np
arr = np.array([1,0,3])
newarr= arr.astype(bool)
print(newarr)

print(newarr.dtype)

[ True False  True]
bool
